import type { OrderCardData } from '../AiAssistant/OrderCard/orderCardTypes';

const today = new Date();
const addDays = (d: number) => {
  const dt = new Date(today);
  dt.setDate(dt.getDate() + d);
  return dt;
};
const fmtDate = (d: Date) => `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`;

export const NLU_DEMO_ORDERS: Record<string, OrderCardData> = {
  'res-food-dine-in': {
    id: 'res-food-dine-in',
    category: 'food',
    categoryLabel: '餐饮',
    productType: 'group_voucher',
    productTypeLabel: '团购券',
    redeemMethod: 'voucher',
    redeemMethodLabel: '到店套餐',
    redeemTypes: ['voucher', 'order'],
    orderStatus: 'unused',
    orderStatusLabel: '待使用',
    productName: '康悦故事足疗SPA 单人精油按摩套餐',
    price: 198.0,
    thumbnail: '💆',
    tags: ['随时退', '免预约'],
    storeName: '康悦故事足疗SPA',
    distance: '1.2km',
    statusText: '待使用',
    statusColor: 'orange',
    actions: [
      { label: '帮我约', type: 'secondary' },
      { label: '🎫 查看券码', type: 'primary' },
    ],
    suggestions: ['可以预约吗', '营业时间是几点', '可以退吗'],
    validDate: `${fmtDate(today)} 至 ${fmtDate(addDays(30))}`,
    voucherInfo: {
      code: '8829 4561 2345',
      number: 'NO.2026070100123456',
      validDate: `${fmtDate(today)} 至 ${fmtDate(addDays(30))}`,
      notes: ['凭券码到店核销使用', '请提前预约', '周末节假日通用'],
    },
  },

  'remind-food-unused': {
    id: 'remind-food-unused',
    category: 'food',
    categoryLabel: '餐饮',
    productType: 'group_voucher',
    productTypeLabel: '团购券',
    redeemMethod: 'voucher',
    redeemMethodLabel: '到店套餐',
    redeemTypes: ['voucher'],
    orderStatus: 'unused',
    orderStatusLabel: '待使用',
    productName: '海底捞火锅 2-3人餐 团购券',
    price: 288.0,
    thumbnail: '🍲',
    tags: ['随时退', '过期退'],
    storeName: '海底捞火锅(陆家嘴店)',
    distance: '2.1km',
    statusText: '待使用',
    statusColor: 'orange',
    actions: [
      { label: '⏰ 使用提醒', type: 'secondary' },
      { label: '🎫 查看券码', type: 'primary' },
    ],
    suggestions: ['有效期到什么时候', '可以退吗', '怎么用'],
    validDate: `${fmtDate(today)} 至 ${fmtDate(addDays(5))}`,
    voucherInfo: {
      code: '6688 2341 5678',
      number: 'NO.2026070100987654',
      validDate: `${fmtDate(today)} 至 ${fmtDate(addDays(5))}`,
      notes: ['凭券码到店核销使用', '节假日通用', '每人限购2份'],
    },
  },

  'pickup-single': {
    id: 'pickup-single',
    category: 'food',
    categoryLabel: '餐饮',
    productType: 'group_voucher',
    productTypeLabel: '团购券',
    redeemMethod: 'self_order',
    redeemMethodLabel: '自提',
    orderStatus: 'waiting_pickup',
    orderStatusLabel: '待取餐',
    productName: '星巴克冰美式 大杯 少冰',
    price: 32.0,
    thumbnail: '☕',
    tags: ['到店取', '免排队'],
    storeName: '星巴克(华润城店)',
    distance: '0.8km',
    statusText: '待取餐',
    statusColor: 'blue',
    extension: {
      type: 'pickup_code',
      title: '取餐信息',
      pickupCode: 'A088',
      pickupTime: '约5分钟后可取餐',
      info: [
        { label: '取餐号', value: 'A088' },
        { label: '预计取餐', value: '约5分钟后可取餐' },
      ],
      steps: [
        { label: '下单成功', state: 'done', time: '10:02' },
        { label: '商家已确认', state: 'done', time: '10:03' },
        { label: '制作中', state: 'done', time: '10:05' },
        { label: '待取餐', state: 'active' },
      ],
    },
    actions: [],
    suggestions: ['门店在哪', '可以改配送吗', '过期能退吗'],
  },

  'pickup-multi-1': {
    id: 'pickup-multi-1',
    category: 'food',
    categoryLabel: '餐饮',
    productType: 'group_voucher',
    productTypeLabel: '团购券',
    redeemMethod: 'self_order',
    redeemMethodLabel: '自提',
    orderStatus: 'waiting_pickup',
    orderStatusLabel: '待取餐',
    productName: '瑞幸生椰拿铁 大杯 热',
    price: 19.9,
    thumbnail: '☕',
    tags: ['到店取', '限时折扣'],
    storeName: '瑞幸咖啡(科技园店)',
    distance: '0.6km',
    statusText: '待取餐',
    statusColor: 'blue',
    extension: {
      type: 'pickup_code',
      title: '取餐信息',
      pickupCode: 'B126',
      pickupTime: '约3分钟后取',
    },
    actions: [],
    suggestions: ['还需要等多久', '帮我催一下', '可以取消吗'],
  },

  'pickup-multi-2': {
    id: 'pickup-multi-2',
    category: 'food',
    categoryLabel: '餐饮',
    productType: 'group_voucher',
    productTypeLabel: '团购券',
    redeemMethod: 'self_order',
    redeemMethodLabel: '自提',
    orderStatus: 'waiting_pickup',
    orderStatusLabel: '待取餐',
    productName: '喜茶多肉葡萄 大杯 少冰',
    price: 29.0,
    thumbnail: '🧋',
    tags: ['到店取', '人气爆款'],
    storeName: '喜茶(万象城店)',
    distance: '1.5km',
    statusText: '待取餐',
    statusColor: 'blue',
    extension: {
      type: 'pickup_code',
      title: '取餐信息',
      pickupCode: 'C305',
      pickupTime: '约8分钟后取',
    },
    actions: [],
    suggestions: ['取餐码在哪', '门店在哪', '可以退款吗'],
  },

  'pickup-voucher-only': {
    id: 'pickup-voucher-only',
    category: 'food',
    categoryLabel: '餐饮',
    productType: 'group_voucher',
    productTypeLabel: '团购券',
    redeemMethod: 'voucher',
    redeemMethodLabel: '到店套餐',
    redeemTypes: ['voucher'],
    orderStatus: 'unused',
    orderStatusLabel: '待使用',
    productName: '【仅券码】单人下午茶套餐 咖啡+蛋糕',
    price: 29.9,
    thumbnail: '☕',
    tags: ['仅券码核销', '随时退', '过期退'],
    storeName: '星巴克(万象城店)',
    distance: '0.8km',
    statusText: '待使用',
    statusColor: 'orange',
    actions: [
      { label: '⏰ 使用提醒', type: 'secondary' },
      { label: '🎫 查看券码', type: 'primary' },
    ],
    suggestions: ['这个券怎么用', '有效期到什么时候', '可以退吗'],
    validDate: `${fmtDate(today)} 至 ${fmtDate(addDays(90))}`,
    voucherInfo: {
      code: '8829 4561 2345',
      number: 'NO.2026070100123456',
      validDate: `${fmtDate(today)} 至 ${fmtDate(addDays(90))}`,
      notes: ['凭券码到店核销使用', '不与其他优惠同享', '周末节假日通用'],
    },
  },

  'pickup-voucher-order': {
    id: 'pickup-voucher-order',
    category: 'food',
    categoryLabel: '餐饮',
    productType: 'group_voucher',
    productTypeLabel: '团购券',
    redeemMethod: 'voucher',
    redeemMethodLabel: '到店套餐',
    redeemTypes: ['voucher', 'order'],
    orderStatus: 'unused',
    orderStatusLabel: '待使用',
    productName: '【券码+点单】双人烤肉套餐 含主食+饮品',
    price: 168.0,
    thumbnail: '🥩',
    tags: ['券码+点单', '随时退'],
    storeName: '西塔老太太烤肉(国贸店)',
    distance: '1.5km',
    statusText: '待使用',
    statusColor: 'orange',
    actions: [
      { label: '🎫 查看券码', type: 'secondary' },
      { label: '立即点单', type: 'primary' },
    ],
    suggestions: ['可以到店点单吗', '怎么用券', '可以退吗'],
    validDate: `${fmtDate(today)} 至 ${fmtDate(addDays(60))}`,
    voucherInfo: {
      code: '6628 3451 8762',
      number: 'NO.2026070100234567',
      validDate: `${fmtDate(today)} 至 ${fmtDate(addDays(60))}`,
      notes: ['到店出示券码核销', '支持扫码点单使用', '周末节假日通用'],
    },
  },

  'pickup-delivery-only': {
    id: 'pickup-delivery-only',
    category: 'food',
    categoryLabel: '餐饮',
    productType: 'group_voucher',
    productTypeLabel: '团购券',
    redeemMethod: 'voucher',
    redeemMethodLabel: '到店套餐',
    redeemTypes: ['delivery'],
    orderStatus: 'unused',
    orderStatusLabel: '待使用',
    productName: '【券码+配送】招牌酸菜鱼套餐 2人份',
    price: 98.0,
    thumbnail: '🐟',
    tags: ['券码+配送', '随时退'],
    storeName: '太二酸菜鱼(三里屯店)',
    distance: '2.3km',
    statusText: '待使用',
    statusColor: 'orange',
    actions: [
      { label: '🎫 查看券码', type: 'secondary' },
      { label: '立即配送', type: 'primary' },
    ],
    suggestions: ['可以外卖配送吗', '配送费多少', '多久送到'],
    validDate: `${fmtDate(today)} 至 ${fmtDate(addDays(45))}`,
    voucherInfo: {
      code: '5521 6783 4521',
      number: 'NO.2026070100345678',
      validDate: `${fmtDate(today)} 至 ${fmtDate(addDays(45))}`,
      notes: ['到店出示券码核销', '支持外卖配送使用', '配送范围3公里内'],
    },
  },

  'pickup-completed-voucher': {
    id: 'pickup-completed-voucher',
    category: 'food',
    categoryLabel: '餐饮',
    productType: 'group_voucher',
    productTypeLabel: '团购券',
    redeemMethod: 'voucher',
    redeemMethodLabel: '到店套餐',
    orderStatus: 'completed',
    orderStatusLabel: '已完成',
    productName: '海底捞火锅 4人套餐 含锅底蘸料',
    price: 288.0,
    thumbnail: '🍲',
    tags: ['随时退'],
    storeName: '海底捞(海岸城店)',
    distance: '2.1km',
    statusText: '已完成',
    statusColor: 'green',
    actions: [
      { label: '评价晒单', type: 'secondary' },
    ],
    suggestions: ['附近还有什么好吃的？', '味道怎么样？', '怎么开发票？'],
  },

  'pickup-completed-offline': {
    id: 'pickup-completed-offline',
    category: 'food',
    categoryLabel: '餐饮',
    productType: 'group_voucher',
    productTypeLabel: '团购券',
    redeemMethod: 'voucher',
    redeemMethodLabel: '到店套餐',
    orderStatus: 'completed',
    orderStatusLabel: '已完成',
    productName: '太二酸菜鱼双人套餐 含米饭饮料',
    price: 158.0,
    thumbnail: '🐟',
    tags: ['堂食', '商家App核销'],
    storeName: '太二酸菜鱼(益田假日店)',
    distance: '3.2km',
    statusText: '已使用',
    statusColor: 'green',
    actions: [
      { label: '评价商家', type: 'secondary' },
    ],
    suggestions: ['味道怎么样？', '怎么开发票？', '有优惠吗？'],
  },

  'pickup-completed-instore': {
    id: 'pickup-completed-instore',
    category: 'food',
    categoryLabel: '餐饮',
    productType: 'group_voucher',
    productTypeLabel: '团购券',
    redeemMethod: 'self_order',
    redeemMethodLabel: '自提',
    orderStatus: 'completed',
    orderStatusLabel: '已完成',
    productName: '麦当劳麦辣鸡腿堡套餐 中薯 可乐',
    price: 39.9,
    thumbnail: '🍔',
    tags: ['到店取', '免排队'],
    storeName: '麦当劳(南山店)',
    distance: '1.2km',
    statusText: '已完成',
    statusColor: 'green',
    extension: {
      type: 'pickup_code',
      title: '取餐信息',
      pickupCode: 'A156',
      pickupTime: '已取餐',
    },
    actions: [],
    suggestions: ['怎么开发票？', '有问题找谁？', '再来一单'],
  },

  'delivery-single-delivering': {
    id: 'delivery-single-delivering',
    category: 'food',
    categoryLabel: '餐饮',
    productType: 'group_voucher',
    productTypeLabel: '团购券',
    redeemMethod: 'delivery',
    redeemMethodLabel: '外卖',
    orderStatus: 'delivering',
    orderStatusLabel: '配送中',
    productName: '巨无霸套餐 中薯 可乐(中) 三人餐',
    price: 88.0,
    thumbnail: '🍔',
    tags: ['随时退', '免预约'],
    storeName: '麦当劳(南山科技园店)',
    distance: '1.2km',
    statusText: '配送中',
    statusColor: 'blue',
    extension: {
      type: 'progress',
      title: '配送进度',
      estimatedTime: '预计15分钟送达',
      steps: [
        { label: '下单成功', state: 'done', time: '11:20' },
        { label: '商家已接单', state: 'done', time: '11:22' },
        { label: '骑手配送中', state: 'active', time: '11:30' },
        { label: '已送达', state: 'pending' },
      ],
      info: [
        { label: '配送骑手', value: '张师傅' },
        { label: '骑手电话', value: '138****8888' },
      ],
    },
    actions: [],
    suggestions: ['还有多久送达？', '骑手到哪了？', '可以改配送地址吗？'],
  },

  'delivery-multi-1': {
    id: 'delivery-multi-1',
    category: 'food',
    categoryLabel: '餐饮',
    productType: 'group_voucher',
    productTypeLabel: '团购券',
    redeemMethod: 'delivery',
    redeemMethodLabel: '外卖',
    orderStatus: 'delivering',
    orderStatusLabel: '配送中',
    productName: '喜茶多肉葡萄 大杯 少冰 标准糖',
    price: 29.0,
    thumbnail: '🧋',
    tags: ['免配送费', '极速达'],
    storeName: '喜茶(万象城店)',
    distance: '1.5km',
    statusText: '配送中',
    statusColor: 'blue',
    extension: {
      type: 'progress',
      title: '配送进度',
      estimatedTime: '预计20分钟送达',
      steps: [
        { label: '下单成功', state: 'done', time: '14:00' },
        { label: '商家已接单', state: 'done', time: '14:02' },
        { label: '骑手配送中', state: 'active', time: '14:10' },
        { label: '已送达', state: 'pending' },
      ],
    },
    actions: [],
    suggestions: ['多久送到', '可以催一下吗', '可以取消吗'],
  },

  'delivery-multi-2': {
    id: 'delivery-multi-2',
    category: 'food',
    categoryLabel: '餐饮',
    productType: 'group_voucher',
    productTypeLabel: '团购券',
    redeemMethod: 'delivery',
    redeemMethodLabel: '外卖',
    orderStatus: 'preparing',
    orderStatusLabel: '制作中',
    productName: '瑞幸生椰拿铁 大杯 热 标准糖',
    price: 19.9,
    thumbnail: '☕',
    tags: ['限时折扣', '免配送费'],
    storeName: '瑞幸咖啡(科技园店)',
    distance: '0.6km',
    statusText: '制作中',
    statusColor: 'blue',
    extension: {
      type: 'progress',
      title: '配送进度',
      estimatedTime: '预计25分钟送达',
      steps: [
        { label: '下单成功', state: 'done', time: '11:20' },
        { label: '商家已接单', state: 'done', time: '11:22' },
        { label: '制作中', state: 'active', time: '11:25' },
        { label: '骑手取餐', state: 'pending' },
        { label: '配送中', state: 'pending' },
        { label: '已送达', state: 'pending' },
      ],
    },
    actions: [],
    suggestions: ['还需要等多久？', '帮我催一下', '可以取消吗？'],
  },

  'delivery-pending-accept': {
    id: 'delivery-pending-accept',
    category: 'food',
    categoryLabel: '餐饮',
    productType: 'group_voucher',
    productTypeLabel: '团购券',
    redeemMethod: 'delivery',
    redeemMethodLabel: '外卖',
    orderStatus: 'pending_accept',
    orderStatusLabel: '待接单',
    productName: '肯德基全家桶 超值家庭套餐',
    price: 99.0,
    thumbnail: '🍗',
    tags: ['随时退', '免预约'],
    storeName: '肯德基(华强北店)',
    distance: '1.5km',
    statusText: '待接单',
    statusColor: 'orange',
    extension: {
      type: 'progress',
      title: '配送进度',
      estimatedTime: '预计2分钟内接单',
      steps: [
        { label: '下单成功', state: 'done', time: '11:20' },
        { label: '商家接单中', state: 'active' },
        { label: '骑手取餐', state: 'pending' },
        { label: '配送中', state: 'pending' },
        { label: '已送达', state: 'pending' },
      ],
    },
    actions: [],
    suggestions: ['多久能接单？', '可以取消吗？', '怎么催单？'],
  },

  'delivery-preparing': {
    id: 'delivery-preparing',
    category: 'food',
    categoryLabel: '餐饮',
    productType: 'group_voucher',
    productTypeLabel: '团购券',
    redeemMethod: 'delivery',
    redeemMethodLabel: '外卖',
    orderStatus: 'preparing',
    orderStatusLabel: '制作中',
    productName: '瑞幸生椰拿铁 大杯 热 标准糖',
    price: 19.9,
    thumbnail: '☕',
    tags: ['限时折扣', '免配送费'],
    storeName: '瑞幸咖啡(科技园店)',
    distance: '0.6km',
    statusText: '制作中',
    statusColor: 'blue',
    extension: {
      type: 'progress',
      title: '配送进度',
      estimatedTime: '预计10分钟后取餐',
      steps: [
        { label: '下单成功', state: 'done', time: '11:20' },
        { label: '商家已接单', state: 'done', time: '11:22' },
        { label: '制作中', state: 'active', time: '11:25' },
        { label: '骑手取餐', state: 'pending' },
        { label: '已送达', state: 'pending' },
      ],
    },
    actions: [],
    suggestions: ['还需要等多久？', '帮我催一下', '可以取消吗？'],
  },

  'delivery-waiting-pickup': {
    id: 'delivery-waiting-pickup',
    category: 'food',
    categoryLabel: '餐饮',
    productType: 'group_voucher',
    productTypeLabel: '团购券',
    redeemMethod: 'delivery',
    redeemMethodLabel: '外卖',
    orderStatus: 'waiting_pickup',
    orderStatusLabel: '待骑手取餐',
    productName: '星巴克冰美式 大杯 少冰',
    price: 32.0,
    thumbnail: '☕',
    tags: ['免配送费', '极速达'],
    storeName: '星巴克(华润城店)',
    distance: '0.8km',
    statusText: '待取餐',
    statusColor: 'blue',
    extension: {
      type: 'progress',
      title: '配送进度',
      estimatedTime: '预计15分钟送达',
      steps: [
        { label: '下单成功', state: 'done', time: '10:02' },
        { label: '商家已确认', state: 'done', time: '10:03' },
        { label: '制作中', state: 'done', time: '10:05' },
        { label: '待骑手取餐', state: 'active' },
        { label: '配送中', state: 'pending' },
        { label: '已送达', state: 'pending' },
      ],
    },
    actions: [],
    suggestions: ['骑手什么时候到', '可以改地址吗', '可以取消吗'],
  },

  'delivery-completed': {
    id: 'delivery-completed',
    category: 'food',
    categoryLabel: '餐饮',
    productType: 'group_voucher',
    productTypeLabel: '团购券',
    redeemMethod: 'delivery',
    redeemMethodLabel: '外卖',
    orderStatus: 'completed',
    orderStatusLabel: '已完成',
    productName: '麦当劳麦辣鸡腿堡套餐 中薯 可乐',
    price: 39.9,
    thumbnail: '🍔',
    tags: ['满减优惠', '免配送费'],
    storeName: '麦当劳(南山店)',
    distance: '1.2km',
    statusText: '已完成',
    statusColor: 'green',
    extension: {
      type: 'delivery_completed',
      title: '配送信息',
      summary: '已为你送达，祝用餐愉快',
      info: [
        { label: '配送时间', value: '2026-07-02 12:35' },
        { label: '配送骑手', value: '张师傅' },
      ],
      steps: [
        { label: '提交订单', state: 'done', time: '11:50' },
        { label: '商家接单', state: 'done', time: '11:52' },
        { label: '商家制作', state: 'done', time: '12:05' },
        { label: '骑手配送', state: 'done', time: '12:20' },
        { label: '已送达', state: 'done', time: '12:35' },
      ],
    },
    actions: [],
    suggestions: ['怎么开发票？', '有问题找谁？', '再来一单'],
  },

  'delivery-exception': {
    id: 'delivery-exception',
    category: 'food',
    categoryLabel: '餐饮',
    productType: 'group_voucher',
    productTypeLabel: '团购券',
    redeemMethod: 'delivery',
    redeemMethodLabel: '外卖',
    orderStatus: 'delivering',
    orderStatusLabel: '配送异常',
    productName: '必胜客超级至尊披萨 双人餐',
    price: 128.0,
    thumbnail: '🍕',
    tags: ['配送中', '异常'],
    storeName: '必胜客(南山店)',
    distance: '1.8km',
    statusText: '配送异常',
    statusColor: 'orange',
    extension: {
      type: 'progress',
      title: '配送进度',
      estimatedTime: '配送延迟',
      steps: [
        { label: '下单成功', state: 'done', time: '12:00' },
        { label: '商家已接单', state: 'done', time: '12:02' },
        { label: '商家出餐延迟', state: 'active', time: '12:30' },
        { label: '骑手配送中', state: 'pending' },
        { label: '已送达', state: 'pending' },
      ],
      info: [
        { label: '异常原因', value: '商家出餐延迟' },
      ],
    },
    actions: [],
    suggestions: ['怎么回事', '可以退款吗', '联系商家'],
  },

  'delivery-non-food': {
    id: 'delivery-non-food',
    category: 'hotel',
    categoryLabel: '酒店',
    productType: 'presale_voucher',
    productTypeLabel: '预售券',
    orderStatus: 'booked',
    orderStatusLabel: '预约成功',
    productName: '【豪华大床房】含双早 免费取消 海景房',
    price: 688.0,
    thumbnail: '🏨',
    tags: ['含双早', '免费取消', '预售券'],
    storeName: '三亚海棠湾君悦酒店',
    distance: '1,234km',
    statusText: '预约成功',
    statusColor: 'green',
    hideStoreLine: true,
    extension: {
      type: 'hotel_stay',
      title: '入住信息',
      hotelInfo: {
        hotelName: '三亚海棠湾君悦酒店',
        checkInDate: '7月15日 周二',
        checkOutDate: '7月17日 周四',
        nights: 2,
      },
      info: [
        { label: '入住时间', value: '2026-07-15 14:00后' },
        { label: '离店时间', value: '2026-07-17 12:00前' },
        { label: '房间数量', value: '1间 · 2人' },
        { label: '预约单号', value: 'YZ2026061800123' },
      ],
    },
    actions: [
      { label: '入住指引', type: 'primary' },
      { label: '帮我改期', type: 'secondary' },
    ],
    suggestions: ['酒店电话是多少？', '可以延迟退房吗？', '有接机服务吗？'],
  },

  'delivery-canceled': {
    id: 'delivery-canceled',
    category: 'food',
    categoryLabel: '餐饮',
    productType: 'group_voucher',
    productTypeLabel: '团购券',
    redeemMethod: 'delivery',
    redeemMethodLabel: '外卖',
    orderStatus: 'cancelled',
    orderStatusLabel: '已取消',
    productName: '肯德基全家桶 超值家庭套餐',
    price: 99.0,
    thumbnail: '🍗',
    tags: ['已取消', '随时退'],
    storeName: '肯德基(华强北店)',
    distance: '1.5km',
    statusText: '已取消',
    statusColor: 'gray',
    actions: [
      { label: '再来一单', type: 'primary' },
    ],
    suggestions: ['为什么取消', '可以重新下单吗', '退款到账了吗'],
  },

  'delivery-refunding': {
    id: 'delivery-refunding',
    category: 'food',
    categoryLabel: '餐饮',
    productType: 'group_voucher',
    productTypeLabel: '团购券',
    redeemMethod: 'delivery',
    redeemMethodLabel: '外卖',
    orderStatus: 'refunding',
    orderStatusLabel: '退款中',
    productName: '必胜客双人披萨套餐',
    price: 128.0,
    thumbnail: '🍕',
    tags: ['退款中'],
    storeName: '必胜客(南山店)',
    distance: '1.8km',
    statusText: '退款中',
    statusColor: 'gray',
    extension: {
      type: 'refund',
      title: '退款进度',
      info: [
        { label: '退款金额', value: '¥128.00' },
        { label: '退款方式', value: '原路退回' },
        { label: '预计到账', value: '1-3个工作日' },
      ],
      steps: [
        { label: '提交申请', state: 'done' },
        { label: '商家审核', state: 'active' },
        { label: '退款到账', state: 'pending' },
      ],
    },
    actions: [],
    suggestions: ['多久能到账？', '可以取消退款吗？', '退到哪里？'],
  },
};

export const getOrderById = (id: string): OrderCardData | undefined => {
  return NLU_DEMO_ORDERS[id];
};
